<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $municipios[] = array(
            array('nome' =>  'Abaíra'),
            array('nome' =>  'Abaré'),
            array('nome' =>  'Acajutiba'),
            array('nome' =>  'Adustina'),
            array('nome' =>  'Água Fria'),
            array('nome' =>  'Érico Cardoso'),
            array('nome' =>  'Aiquara'),
            array('nome' =>  'Alagoinhas'),
            array('nome' =>  'Alcobaça'),
            array('nome' =>  'Almadina'),
            array('nome' =>  'Amargosa'),
            array('nome' =>  'Amélia Rodrigues'),
            array('nome' =>  'América Dourada'),
            array('nome' =>  'Anagé'),
            array('nome' =>  'Andaraí'),
            array('nome' =>  'Andorinha'),
            array('nome' =>  'Angical'),
            array('nome' =>  'Anguera'),
            array('nome' =>  'Antas'),
            array('nome' =>  'Antônio Cardoso'),
            array('nome' =>  'Antônio Gonçalves'),
            array('nome' =>  'Aporá'),
            array('nome' =>  'Apuarema'),
            array('nome' =>  'Aracatu'),
            array('nome' =>  'Araças'),
            array('nome' =>  'Araci'),
            array('nome' =>  'Aramari'),
            array('nome' =>  'Arataca'),
            array('nome' =>  'Aratuípe'),
            array('nome' =>  'Aurelino Leal'),
            array('nome' =>  'Baianópolis'),
            array('nome' =>  'Baixa Grande'),
            array('nome' =>  'Banzaê'),
            array('nome' =>  'Barra'),
            array('nome' =>  'Barra da Estiva'),
            array('nome' =>  'Barra do Choça'),
            array('nome' =>  'Barra do Mendes'),
            array('nome' =>  'Barra do Rocha'),
            array('nome' =>  'Barreiras'),
            array('nome' =>  'Barro Alto'),
            array('nome' =>  'Barrocas'),
            array('nome' =>  'Governador Lomanto Júnior'),
            array('nome' =>  'Belmonte'),
            array('nome' =>  'Belo Campo'),
            array('nome' =>  'Biritinga'),
            array('nome' =>  'Boa Nova'),
            array('nome' =>  'Boa Vista do Tupim'),
            array('nome' =>  'Bom Jesus da Lapa'),
            array('nome' =>  'Bom Jesus da Serra'),
            array('nome' =>  'Boninal'),
            array('nome' =>  'Bonito'),
            array('nome' =>  'Boquira'),
            array('nome' =>  'Botuporã'),
            array('nome' =>  'Brejões'),
            array('nome' =>  'Brejolândia'),
            array('nome' =>  'Brotas de Macaúbas'),
            array('nome' =>  'Brumado'),
            array('nome' =>  'Buerarema'),
            array('nome' =>  'Buritirama'),
            array('nome' =>  'Caatiba'),
            array('nome' =>  'Cabaceiras do Paraguaçu'),
            array('nome' =>  'Cachoeira'),
            array('nome' =>  'Caculé'),
            array('nome' =>  'Caém'),
            array('nome' =>  'Caetanos'),
            array('nome' =>  'Caetité'),
            array('nome' =>  'Cafarnaum'),
            array('nome' =>  'Cairu'),
            array('nome' =>  'Caldeirão Grande'),
            array('nome' =>  'Camacan'),
            array('nome' =>  'Camaçari'),
            array('nome' =>  'Camamu'),
            array('nome' =>  'Campo Alegre de Lourdes'),
            array('nome' =>  'Campo Formoso'),
            array('nome' =>  'Canápolis'),
            array('nome' =>  'Canarana'),
            array('nome' =>  'Canavieiras'),
            array('nome' =>  'Candeal'),
            array('nome' =>  'Candeias'),
            array('nome' =>  'Candiba'),
            array('nome' =>  'Cândido Sales'),
            array('nome' =>  'Cansanção'),
            array('nome' =>  'Canudos'),
            array('nome' =>  'Capela do Alto Alegre'),
            array('nome' =>  'Capim Grosso'),
            array('nome' =>  'Caraíbas'),
            array('nome' =>  'Caravelas'),
            array('nome' =>  'Cardeal da Silva'),
            array('nome' =>  'Carinhanha'),
            array('nome' =>  'Casa Nova'),
            array('nome' =>  'Castro Alves'),
            array('nome' =>  'Catolândia'),
            array('nome' =>  'Catu'),
            array('nome' =>  'Caturama'),
            array('nome' =>  'Central'),
            array('nome' =>  'Chorrochó'),
            array('nome' =>  'Cícero Dantas'),
            array('nome' =>  'Cipó'),
            array('nome' =>  'Coaraci'),
            array('nome' =>  'Cocos'),
            array('nome' =>  'Conceição da Feira'),
            array('nome' =>  'Conceição do Almeida'),
            array('nome' =>  'Conceição do Coité'),
            array('nome' =>  'Conceição do Jacuípe'),
            array('nome' =>  'Conde'),
            array('nome' =>  'Condeúba'),
            array('nome' =>  'Contendas do Sincorá'),
            array('nome' =>  'Coração de Maria'),
            array('nome' =>  'Cordeiros'),
            array('nome' =>  'Coribe'),
            array('nome' =>  'Coronel João Sá'),
            array('nome' =>  'Correntina'),
            array('nome' =>  'Cotegipe'),
            array('nome' =>  'Cravolândia'),
            array('nome' =>  'Crisópolis'),
            array('nome' =>  'Cristópolis'),
            array('nome' =>  'Cruz das Almas'),
            array('nome' =>  'Curaçá'),
            array('nome' =>  'Dário Meira'),
            array('nome' =>  'Dias D\´Ávila'),
            array('nome' =>  'Dom Basílio'),
            array('nome' =>  'Dom Macedo Costa'),
            array('nome' =>  'Elísio Medrado'),
            array('nome' =>  'Encruzilhada'),
            array('nome' =>  'Entre Rios'),
            array('nome' =>  'Esplanada'),
            array('nome' =>  'Euclides da Cunha'),
            array('nome' =>  'Eunápolis'),
            array('nome' =>  'Fátima'),
            array('nome' =>  'Feira da Mata'),
            array('nome' =>  'Feira de Santana'),
            array('nome' =>  'Filadélfia'),
            array('nome' =>  'Firmino Alves'),
            array('nome' =>  'Floresta Azul'),
            array('nome' =>  'Formosa do Rio Preto'),
            array('nome' =>  'Gandu'),
            array('nome' =>  'Gavião'),
            array('nome' =>  'Gentio do Ouro'),
            array('nome' =>  'Glória'),
            array('nome' =>  'Gongogi'),
            array('nome' =>  'Governador Mangabeira'),
            array('nome' =>  'Guajeru'),
            array('nome' =>  'Guanambi'),
            array('nome' =>  'Guaratinga'),
            array('nome' =>  'Heliópolis'),
            array('nome' =>  'Iaçu'),
            array('nome' =>  'Ibiassucê'),
            array('nome' =>  'Ibicaraí'),
            array('nome' =>  'Ibicoara'),
            array('nome' =>  'Ibicuí'),
            array('nome' =>  'Ibipeba'),
            array('nome' =>  'Ibipitanga'),
            array('nome' =>  'Ibiquera'),
            array('nome' =>  'Ibirapitanga'),
            array('nome' =>  'Ibirapuã'),
            array('nome' =>  'Ibirataia'),
            array('nome' =>  'Ibitiara'),
            array('nome' =>  'Ibititá'),
            array('nome' =>  'Ibotirama'),
            array('nome' =>  'Ichu'),
            array('nome' =>  'Igaporã'),
            array('nome' =>  'Igrapiúna'),
            array('nome' =>  'Iguaí'),
            array('nome' =>  'Ilhéus'),
            array('nome' =>  'Inhambupe'),
            array('nome' =>  'Ipecaetá'),
            array('nome' =>  'Ipiaú'),
            array('nome' =>  'Ipirá'),
            array('nome' =>  'Ipupiara'),
            array('nome' =>  'Irajuba'),
            array('nome' =>  'Iramaia'),
            array('nome' =>  'Iraquara'),
            array('nome' =>  'Irará'),
            array('nome' =>  'Irecê'),
            array('nome' =>  'Itabela'),
            array('nome' =>  'Itaberaba'),
            array('nome' =>  'Itabuna'),
            array('nome' =>  'Itacaré'),
            array('nome' =>  'Itaeté'),
            array('nome' =>  'Itagi'),
            array('nome' =>  'Itagibá'),
            array('nome' =>  'Itagimirim'),
            array('nome' =>  'Itaguaçu da Bahia'),
            array('nome' =>  'Itaju do Colônia'),
            array('nome' =>  'Itajuípe'),
            array('nome' =>  'Itamaraju'),
            array('nome' =>  'Itamari'),
            array('nome' =>  'Itambé'),
            array('nome' =>  'Itanagra'),
            array('nome' =>  'Itanhém'),
            array('nome' =>  'Itaparica'),
            array('nome' =>  'Itapé'),
            array('nome' =>  'Itapebi'),
            array('nome' =>  'Itapetinga'),
            array('nome' =>  'Itapicuru'),
            array('nome' =>  'Itapitanga'),
            array('nome' =>  'Itaquara'),
            array('nome' =>  'Itarantim'),
            array('nome' =>  'Itatim'),
            array('nome' =>  'Itiruçu'),
            array('nome' =>  'Itiúba'),
            array('nome' =>  'Itororó'),
            array('nome' =>  'Ituaçu'),
            array('nome' =>  'Ituberá'),
            array('nome' =>  'Iuiú'),
            array('nome' =>  'Jaborandi'),
            array('nome' =>  'Jacaraci'),
            array('nome' =>  'Jacobina'),
            array('nome' =>  'Jaguaquara'),
            array('nome' =>  'Jaguarari'),
            array('nome' =>  'Jaguaripe'),
            array('nome' =>  'Jandaíra'),
            array('nome' =>  'Jequié'),
            array('nome' =>  'Jeremoabo'),
            array('nome' =>  'Jiquiriçá'),
            array('nome' =>  'Jitaúna'),
            array('nome' =>  'João Dourado'),
            array('nome' =>  'Juazeiro'),
            array('nome' =>  'Jucuruçu'),
            array('nome' =>  'Jussara'),
            array('nome' =>  'Jussari'),
            array('nome' =>  'Jussiape'),
            array('nome' =>  'Lafaiete Coutinho'),
            array('nome' =>  'Lagoa Real'),
            array('nome' =>  'Laje'),
            array('nome' =>  'Lajedão'),
            array('nome' =>  'Lajedinho'),
            array('nome' =>  'Lajedo do Tabocal'),
            array('nome' =>  'Lamarão'),
            array('nome' =>  'Lapão'),
            array('nome' =>  'Lauro de Freitas'),
            array('nome' =>  'Lençóis'),
            array('nome' =>  'Licínio de Almeida'),
            array('nome' =>  'Livramento de Nossa Senhora'),
            array('nome' =>  'Luís Eduardo Magalhães'),
            array('nome' =>  'Macajuba'),
            array('nome' =>  'Macarani'),
            array('nome' =>  'Macaúbas'),
            array('nome' =>  'Macururé'),
            array('nome' =>  'Madre de Deus'),
            array('nome' =>  'Maetinga'),
            array('nome' =>  'Maiquinique'),
            array('nome' =>  'Mairi'),
            array('nome' =>  'Malhada'),
            array('nome' =>  'Malhada de Pedras'),
            array('nome' =>  'Manoel Vitorino'),
            array('nome' =>  'Mansidão'),
            array('nome' =>  'Maracás'),
            array('nome' =>  'Maragogipe'),
            array('nome' =>  'Maraú'),
            array('nome' =>  'Marcionílio Souza'),
            array('nome' =>  'Mascote'),
            array('nome' =>  'Mata de São João'),
            array('nome' =>  'Matina'),
            array('nome' =>  'Medeiros Neto'),
            array('nome' =>  'Miguel Calmon'),
            array('nome' =>  'Milagres'),
            array('nome' =>  'Mirangaba'),
            array('nome' =>  'Mirante'),
            array('nome' =>  'Monte Santo'),
            array('nome' =>  'Morpará'),
            array('nome' =>  'Morro do Chapéu'),
            array('nome' =>  'Mortugaba'),
            array('nome' =>  'Mucugê'),
            array('nome' =>  'Mucuri'),
            array('nome' =>  'Mulungu do Morro'),
            array('nome' =>  'Mundo Novo'),
            array('nome' =>  'Muniz Ferreira'),
            array('nome' =>  'Muquém de São Francisco'),
            array('nome' =>  'Muritiba'),
            array('nome' =>  'Mutuípe'),
            array('nome' =>  'Nazaré'),
            array('nome' =>  'Nilo Peçanha'),
            array('nome' =>  'Nordestina'),
            array('nome' =>  'Nova Canaã'),
            array('nome' =>  'Nova Fátima'),
            array('nome' =>  'Nova Ibiá'),
            array('nome' =>  'Nova Itarana'),
            array('nome' =>  'Nova Redenção'),
            array('nome' =>  'Nova Soure'),
            array('nome' =>  'Nova Viçosa'),
            array('nome' =>  'Novo Horizonte'),
            array('nome' =>  'Novo Triunfo'),
            array('nome' =>  'Olindina'),
            array('nome' =>  'Oliveira Dos Brejinhos'),
            array('nome' =>  'Ouriçangas'),
            array('nome' =>  'Ourolândia'),
            array('nome' =>  'Palmas de Monte Alto'),
            array('nome' =>  'Palmeiras'),
            array('nome' =>  'Paramirim'),
            array('nome' =>  'Paratinga'),
            array('nome' =>  'Paripiranga'),
            array('nome' =>  'Pau Brasil'),
            array('nome' =>  'Paulo Afonso'),
            array('nome' =>  'Pé de Serra'),
            array('nome' =>  'Pedrão'),
            array('nome' =>  'Pedro Alexandre'),
            array('nome' =>  'Piatã'),
            array('nome' =>  'Pilão Arcado'),
            array('nome' =>  'Pindaí'),
            array('nome' =>  'Pindobaçu'),
            array('nome' =>  'Pintadas'),
            array('nome' =>  'Piraí do Norte'),
            array('nome' =>  'Piripá'),
            array('nome' =>  'Piritiba'),
            array('nome' =>  'Planaltino'),
            array('nome' =>  'Planalto'),
            array('nome' =>  'Poções'),
            array('nome' =>  'Pojuca'),
            array('nome' =>  'Ponto Novo'),
            array('nome' =>  'Porto Seguro'),
            array('nome' =>  'Potiraguá'),
            array('nome' =>  'Prado'),
            array('nome' =>  'Presidente Dutra'),
            array('nome' =>  'Presidente Jânio Quadros'),
            array('nome' =>  'Presidente Tancredo Neves'),
            array('nome' =>  'Queimadas'),
            array('nome' =>  'Quijingue'),
            array('nome' =>  'Quixabeira'),
            array('nome' =>  'Rafael Jambeiro'),
            array('nome' =>  'Remanso'),
            array('nome' =>  'Retirolândia'),
            array('nome' =>  'Riachão Das Neves'),
            array('nome' =>  'Riachão do Jacuípe'),
            array('nome' =>  'Riacho de Santana'),
            array('nome' =>  'Ribeira do Amparo'),
            array('nome' =>  'Ribeira do Pombal'),
            array('nome' =>  'Ribeirão do Largo'),
            array('nome' =>  'Rio de Contas'),
            array('nome' =>  'Rio do Antônio'),
            array('nome' =>  'Rio do Pires'),
            array('nome' =>  'Rio Real'),
            array('nome' =>  'Rodelas'),
            array('nome' =>  'Ruy Barbosa'),
            array('nome' =>  'Salinas da Margarida'),
            array('nome' =>  'Salvador'),
            array('nome' =>  'Santa Bárbara'),
            array('nome' =>  'Santa Brígida'),
            array('nome' =>  'Santa Cruz Cabrália'),
            array('nome' =>  'Santa Cruz da Vitória'),
            array('nome' =>  'Santa Inês'),
            array('nome' =>  'Santaluz'),
            array('nome' =>  'Santa Luzia'),
            array('nome' =>  'Santa Maria da Vitória'),
            array('nome' =>  'Santana'),
            array('nome' =>  'Santanópolis'),
            array('nome' =>  'Santa Rita de Cássia'),
            array('nome' =>  'Santa Teresinha'),
            array('nome' =>  'Santo Amaro'),
            array('nome' =>  'Santo Antônio de Jesus'),
            array('nome' =>  'Santo Estêvão'),
            array('nome' =>  'São Desidério'),
            array('nome' =>  'São Domingos'),
            array('nome' =>  'São Félix'),
            array('nome' =>  'São Félix do Coribe'),
            array('nome' =>  'São Felipe'),
            array('nome' =>  'São Francisco do Conde'),
            array('nome' =>  'São Gabriel'),
            array('nome' =>  'São Gonçalo dos Campos'),
            array('nome' =>  'São José da Vitória'),
            array('nome' =>  'São José do Jacuípe'),
            array('nome' =>  'São Miguel das Matas'),
            array('nome' =>  'São Sebastião do Passé'),
            array('nome' =>  'Sapeaçu'),
            array('nome' =>  'Sátiro Dias'),
            array('nome' =>  'Saubara'),
            array('nome' =>  'Saúde'),
            array('nome' =>  'Seabra'),
            array('nome' =>  'Sebastião Laranjeiras'),
            array('nome' =>  'Senhor do Bonfim'),
            array('nome' =>  'Serra do Ramalho'),
            array('nome' =>  'Sento Sé'),
            array('nome' =>  'Serra Dourada'),
            array('nome' =>  'Serra Preta'),
            array('nome' =>  'Serrinha'),
            array('nome' =>  'Serrolândia'),
            array('nome' =>  'Simões Filho'),
            array('nome' =>  'Sítio do Mato'),
            array('nome' =>  'Sítio do Quinto'),
            array('nome' =>  'Sobradinho'),
            array('nome' =>  'Souto Soares'),
            array('nome' =>  'Tabocas do Brejo Velho'),
            array('nome' =>  'Tanhaçu'),
            array('nome' =>  'Tanque Novo'),
            array('nome' =>  'Tanquinho'),
            array('nome' =>  'Taperoá'),
            array('nome' =>  'Tapiramutá'),
            array('nome' =>  'Teixeira de Freitas'),
            array('nome' =>  'Teodoro Sampaio'),
            array('nome' =>  'Teofilândia'),
            array('nome' =>  'Teolândia'),
            array('nome' =>  'Terra Nova'),
            array('nome' =>  'Tremedal'),
            array('nome' =>  'Tucano'),
            array('nome' =>  'Uauá'),
            array('nome' =>  'Ubaíra'),
            array('nome' =>  'Ubaitaba'),
            array('nome' =>  'Ubatã'),
            array('nome' =>  'Uibaí'),
            array('nome' =>  'Umburanas'),
            array('nome' =>  'Una'),
            array('nome' =>  'Urandi'),
            array('nome' =>  'Uruçuca'),
            array('nome' =>  'Utinga'),
            array('nome' =>  'Valença'),
            array('nome' =>  'Valente'),
            array('nome' =>  'Várzea da Roça'),
            array('nome' =>  'Várzea do Poço'),
            array('nome' =>  'Várzea Nova'),
            array('nome' =>  'Varzedo'),
            array('nome' =>  'Vera Cruz'),
            array('nome' =>  'Vereda'),
            array('nome' =>  'Vitória da Conquista'),
            array('nome' =>  'Wagner'),
            array('nome' =>  'Wanderley'),
            array('nome' =>  'Wenceslau Guimarães'),
            array('nome' =>  'Xique-Xique'),
        );
        foreach ($municipios as $municipio) {
            DB::table('municipios')->insert($municipio);
        }

        $campuses[] = array(
            array('nome' => 'Campus Avançado'),
            array('nome' => 'Pólo EAD'),
            array('nome' => 'Pólo Parfor'),
            array('nome' => 'Adm. Central'),
            array('nome' => 'Campus I'),
            array('nome' => 'Campus II'),
            array('nome' => 'Campus III'),
            array('nome' => 'Campus IV'),
            array('nome' => 'Campus V'),
            array('nome' => 'Campus VI'),
            array('nome' => 'Campus VII'),
            array('nome' => 'Campus VIII'),
            array('nome' => 'Campus IX'),
            array('nome' => 'Campus X'),
            array('nome' => 'Campus XI'),
            array('nome' => 'Campus XII'),
            array('nome' => 'Campus XIII'),
            array('nome' => 'Campus XIV'),
            array('nome' => 'Campus XV'),
            array('nome' => 'Campus XVI'),
            array('nome' => 'Campus XVII'),
            array('nome' => 'Campus XVIII'),
            array('nome' => 'Campus XIX'),
            array('nome' => 'Campus XX'),
            array('nome' => 'Campus XXI'),
            array('nome' => 'Campus XXII'),
            array('nome' => 'Campus XXIII'),
            array('nome' => 'Campus XXIV'),
            array('nome' => 'CPEDR'),
            array('nome' => 'CEEC'),
            array('nome' => 'CEPAIA'),
            array('nome' => 'CPT'),
            array('nome' => 'CEL-FM'),
            array('nome' => 'CESDE'),
            array('nome' => 'CAAPA'),
            array('nome' => 'CDTA'),
            array('nome' => 'CASULO'),
            array('nome' => 'CEESAR'),
            array('nome' => 'OPARÁ'),
            array('nome' => 'CEGRES/DIADORIM'),
            array('nome' => 'CEICR'),
            array('nome' => 'CEPITI'),
            array('nome' => 'CAECDT'),
            array('nome' => 'CRDH'),
            array('nome' => 'CPDCV'),
        );

        foreach ($campuses as $campus){
            DB::table('campuses')->insert($campus);
        }

        $departamentos[] = array(
            array('nome'=> 'Administração Central', 'sigla' => 'AdmCentral'),
            array('nome'=> 'Departamento de Ciências da Vida', 'sigla' => 'DCV'),
            array('nome'=> 'Departamento de Ciências Exatas e da Terra', 'sigla' => 'DCET'),
            array('nome'=> 'Departamento de Ciências Humanas', 'sigla' => 'DCH'),
            array('nome'=> 'Departamento de Ciências Humanas e Tecnologias', 'sigla' => 'DCHT'),
            array('nome'=> 'Departamento de Educação', 'sigla' => 'DEDC'),
            array('nome'=> 'Departamento de Linguística, Literatura e Artes', 'sigla' => 'DLLARTES'),
            array('nome'=> 'Departamento de Tecnologia e Ciências Sociais', 'sigla' => 'DTCS'),
            array('nome'=> 'Unidade de Ensino a Distância', 'sigla' => 'EAD - UNEAD'),
            array('nome'=> 'Plano Nac. de Form. Dos Prof. Da Educação Básica', 'sigla' => 'PARFOR'),
        );

        foreach ($departamentos as $departamento){
            DB::table('departamentos')->insert($departamento);
        }

        $cursos[] = array(
            array('nome' => 'Administração'),
            array('nome' => 'Administração Pública'),
            array('nome' => 'Agroecologia'),
            array('nome' => 'Arqueologia'),
            array('nome' => 'Biologia'),
            array('nome' => 'Ciências Biológicas'),
            array('nome' => 'Ciências Contábeis'),
            array('nome' => 'Ciências da Computação'),
            array('nome' => 'Ciências Sociais'),
            array('nome' => 'Comunicação Social / Rádio e TV'),
            array('nome' => 'Cursos Livres Online'),
            array('nome' => 'Design'),
            array('nome' => 'Direito'),
            array('nome' => 'Educação Digital'),
            array('nome' => 'Educação Física'),
            array('nome' => 'Educação Inclusiva'),
            array('nome' => 'Enfermagem'),
            array('nome' => 'Engenharia Agroindustrial'),
            array('nome' => 'Engenharia Agronômica'),
            array('nome' => 'Engenharia de Bioprocessos e Biotecnologia'),
            array('nome' => 'Engenharia de Minas'),
            array('nome' => 'Engenharia de Pesca'),
            array('nome' => 'Engenharia de Produção Civil'),
            array('nome' => 'Engenharia Sanitária e Ambiental'),
            array('nome' => 'Espanhol'),
            array('nome' => 'Farmácia'),
            array('nome' => 'Filosofia'),
            array('nome' => 'Física'),
            array('nome' => 'Fisioterapia'),
            array('nome' => 'Fonoaudiologia'),
            array('nome' => 'Geografia'),
            array('nome' => 'História'),
            array('nome' => 'Inglês'),
            array('nome' => 'Interdisciplinar em Estudos Sociais e Humanidades'),
            array('nome' => 'Jogos Digitais'),
            array('nome' => 'Jornalismo em Multimeios'),
            array('nome' => 'Letras / Língua Espanhola e Literaturas'),
            array('nome' => 'Letras / Língua Francesa e Literaturas'),
            array('nome' => 'Letras / Língua Inglesa e Literaturas'),
            array('nome' => 'Letras / Língua Portuguesa e Literaturas'),
            array('nome' => 'Letras Espanhol'),
            array('nome' => 'Letras Inglês'),
            array('nome' => 'Letras Português'),
            array('nome' => 'Licenciatura em Letras - Língua Espanhola e suas Literaturas'),
            array('nome' => 'Licenciatura em Letras - Língua Inglesa e suas Literaturas'),
            array('nome' => 'Licenciatura em Letras - Língua Portuguesa e suas Literaturas'),
            array('nome' => 'Licenciatura em Química'),
            array('nome' => 'Licenciatura Intercultural em Educação Escolar Indígena - LICEEI'),
            array('nome' => 'Matemática'),
            array('nome' => 'Medicina'),
            array('nome' => 'Medicina Veterinária'),
            array('nome' => 'Música'),
            array('nome' => 'Nutrição'),
            array('nome' => 'Pedagogia'),
            array('nome' => 'Pedagogia Intercultural Indígena'),
            array('nome' => 'Português'),
            array('nome' => 'Psicologia'),
            array('nome' => 'Química'),
            array('nome' => 'Relações Públicas'),
            array('nome' => 'Sistemas de Informação'),
            array('nome' => 'Teatro'),
            array('nome' => 'Turismo'),
            array('nome' => 'Turismo e Hotelaria'),
            array('nome' => 'Urbanismo'),
            array('nome' => 'Pós-Graduação em Agroecologia e Desenvolvimento Territorial (PPGADT) '),
            array('nome' => 'Pós-Graduação em Agronomia: Horticultura Irrigada (PPGHI)'),
            array('nome' => 'Pós-Graduação em Análise Ambiental e Gestão Sustentável do Território'),
            array('nome' => 'Pós-Graduação em Biociências e Biodiversidade: Ecologia e Conservação Ambiental (BIOECOA)'),
            array('nome' => 'Pós-Graduação em Biodiversidade Vegetal (PPGBVeg)'),
            array('nome' => 'Pós-Graduação em Biologia Vegetal'),
            array('nome' => 'Pós-Graduação em Ciências Farmacêuticas (PPGFARMA)'),
            array('nome' => 'Pós-Graduação em Crítica Cultural (Pós-Crítica)'),
            array('nome' => 'Pós-Graduação em Ecologia Humana e Gestão Socioambiental (PPGEcoH)'),
            array('nome' => 'Pós-Graduação em Educação a Distância'),
            array('nome' => 'Pós-Graduação em Educação Ambiental, Biodiversidade e Cultura Regional (EABCR)'),
            array('nome' => 'Pós-Graduação em Educação de Jovens e Adultos (MPEJA)'),
            array('nome' => 'Pós-Graduação em Educação do Campo'),
            array('nome' => 'Pós-Graduação em Educação e Contemporaneidade (PPGEduC)'),
            array('nome' => 'Pós-Graduação em Educação e Diversidade (MPED)'),
            array('nome' => 'Pós-Graduação em Educação e Diversidade Étnico-Racial'),
            array('nome' => 'Pós-Graduação em Educação e Meio Ambiente'),
            array('nome' => 'Pós-Graduação em Educação Infantil'),
            array('nome' => 'Pós-Graduação em Educação Matemática'),
            array('nome' => 'Pós-Graduação em Educação Matemática e Contemporaneidade (PPGEEMC)'),
            array('nome' => 'Pós-Graduação em Educação, Cultura e Territórios Semiáridos (PPGESA)'),
            array('nome' => 'Pós-Graduação em Educação, Processos Tecnológicos e Práticas Inovadoras'),
            array('nome' => 'Pós-Graduação em Enfermagem em Emergência e Unidade de Terapia Intensiva'),
            array('nome' => 'Pós-Graduação em Ensino de Física (ProfFísica)'),
            array('nome' => 'Pós-Graduação em Ensino de História (ProfHistoria)'),
            array('nome' => 'Pós-Graduação em Ensino de Língua Portuguesa e Literaturas'),
            array('nome' => 'Pós-Graduação em Ensino, Linguagem  e Sociedade  (PPGELS)'),
            array('nome' => 'Pós-Graduação em Estudo de Linguagens (PPGEL)'),
            array('nome' => 'Pós-Graduação em Estudos Africanos e Representações da África'),
            array('nome' => 'Pós-Graduação em Estudos Africanos, Povos Indígenas e Culturas Negras (PPGEAFIN)'),
            array('nome' => 'Pós-Graduação em Estudos Literários e Linguística Aplicada ao Ensino'),
            array('nome' => 'Pós-Graduação em Estudos Sociais e Humanidades'),
            array('nome' => 'Pós-Graduação em Estudos Territoriais (PROET)'),
            array('nome' => 'Pós-Graduação em Gênero, Raça, Etnia e Sexualidades na Formação de Educadores'),
            array('nome' => 'Pós-Graduação em Geografia e Desenvolvimento Territorial'),
            array('nome' => 'Pós-Graduação em Gestão do Patrimônio Histórico-Cultural e Ambiental '),
            array('nome' => 'Pós-Graduação em Gestão e Políticas Públicas para a Educação Básica e a Implantação do Observatório de Gestão de Políticas Públicas para a Educação Básica'),
            array('nome' => 'Pós-Graduação em Gestão e Tecnologia Aplicadas à Educação (GESTEC)'),
            array('nome' => 'Pós-Graduação em Gestão em Saúde'),
            array('nome' => 'Pós-Graduação em Gestão Estratégica das Organizações'),
            array('nome' => 'Pós-Graduação em Gestão Estratégica e Negócios'),
            array('nome' => 'Pós-Graduação em Gestão Pública'),
            array('nome' => 'Pós-Graduação em Gestão Pública Municipal'),
            array('nome' => 'Pós-Graduação em História (Pós-História)'),
            array('nome' => 'Pós-Graduação em História Regional e Local (PPGHIS)'),
            array('nome' => 'Pós-Graduação em História Social da Cultura'),
            array('nome' => 'Pós-Graduação em História, Cultura e Sociedade'),
            array('nome' => 'Pós-Graduação em História, Educação e Sociedade'),
            array('nome' => 'Pós-Graduação em Intervenção Educativa e Social (MPIES)'),
            array('nome' => 'Pós-Graduação em Letras (PPGL)                                                                                                                 '),
            array('nome' => 'Pós-Graduação em Linguística Aplicada ao Ensino da Língua Portuguesa'),
            array('nome' => 'Pós-Graduação em Literatura Brasileira'),
            array('nome' => 'Pós-Graduação em Literatura Brasileira: Formação do Cânone e Contrapontos Críticos'),
            array('nome' => 'Pós-Graduação em Matemática Aplicada'),
            array('nome' => 'Pós-Graduação em Metodologia do Ensino-aprendizagem de Línguas Estrangeiras '),
            array('nome' => 'Pós-Graduação em Política do Planejamento Pedagógico: Currículo, Didática e Avaliação'),
            array('nome' => 'Pós-Graduação em Pós-Graduação em Formação de Professores em Letras/LIBRAS'),
            array('nome' => 'Pós-Graduação em Práticas Docentes Interdisciplinares'),
            array('nome' => 'Pós-Graduação em Produção Vegetal no Cerrado'),
            array('nome' => 'Pós-Graduação em Química Aplicada (PGQA)'),
            array('nome' => 'Pós-Graduação em Saúde Coletiva  (MEPISCO)'),
            array('nome' => 'Pós-Graduação Modelagem e Simulação de Biossistemas (PPGMSB)                                                         '),
            array('nome' => 'Pós-Graduação Multi-Institucional Multidisciplinar em Difusão do Conhecimento (DMMDC)'),
            array('nome' => 'Pós-Graduação Profissional em Letras (Profletras)'),
            array('nome' => 'Pós-Graduação Residência Multiprofissional em Saúde'),
        );

        foreach ($cursos as $curso){
            DB::table('cursos')->insert($curso);
        }

        $userAdmin[] = array(
            array(
                'name' => 'Claudio Souza',
                'email' => 'claudiosouza.cia@gmail.com',
                'email_verified_at' => now(),
                'password'=> bcrypt('91316445'),
                'matricula' => '925294',
                'tipo' => 't',
                'role' => User::ROLE_ADMIN,
                'genero' => 'm',
                'nome_social' => 'Claudio Souza',
                'raca' => 'brt',
                'celular' => '71999094687',
                'municipio_id' => 336,
                'campus_id' => 4,
                'departamento_id' => 1,
                'autoriz' => 's',
            ),
            array(
                'name' => 'Staff Teste',
                'email' => 'stafteste@user.com',
                'email_verified_at' => now(),
                'password'=> bcrypt('91316445'),
                'matricula' => '925295',
                'tipo' => 'p',
                'role' => User::ROLE_STAFF,
                'genero' => 'f',
                'nome_social' => 'Staff Teste',
                'raca' => 'prt',
                'celular' => '71999094688',
                'municipio_id' => 336,
                'campus_id' => 4,
                'departamento_id' => 1,
                'autoriz' => 's',
            ),
            array(
                'name' => 'Redat Teste',
                'email' => 'redatteste@user.com',
                'email_verified_at' => now(),
                'password'=> bcrypt('91316445'),
                'matricula' => '925296',
                'tipo' => 'p',
                'role' => User::ROLE_REDAT,
                'genero' => 'm',
                'nome_social' => 'Redat Teste',
                'raca' => 'brt',
                'celular' => '71999094689',
                'municipio_id' => 336,
                'campus_id' => 4,
                'departamento_id' => 1,
                'autoriz' => 's',
            ),
            array(
                'name' => 'Aluno Teste',
                'email' => 'alunoteste@user.com',
                'email_verified_at' => now(),
                'password'=> bcrypt('91316445'),
                'matricula' => '925297',
                'tipo' => 'a',
                'role' => User::ROLE_CLIENTE,
                'genero' => 'f',
                'nome_social' => 'Aluno Teste',
                'raca' => 'prt',
                'celular' => '71999094690',
                'municipio_id' => 336,
                'campus_id' => 4,
                'departamento_id' => 3,
                'autoriz' => 's',
            ),

        );
        foreach ($userAdmin as $user) {
            DB::table('users')->insert($user);
        }

        $dimensions[] = array(
            array(
                'name' => 'Graduação',
                'sigla' => 'Grad',
                'introd' => 'Dimensão que se refere ao objeto central da UNEB, que engloba os cursos de graduação. Não por acaso está listada como primeira, mostrando a importância merecida',
                'user_id' => 1,
                ),
            array(
                'name' => 'Pós-Graduação',
                'sigla' => 'Pós',
                'introd' => 'Consequuntur inventore voluptates consequatur aut vel et. Eos doloribus expedita. Sapiente atque consequatur minima nihil quae aspernatur quo suscipit voluptatem',
                'user_id' => 1,
            ),
            array(
                'name' => 'Educação a Distância',
                'sigla' => 'EAD',
                'introd' => 'Consequuntur inventore voluptates consequatur aut vel et. Eos doloribus expedita. Sapiente atque consequatur minima nihil quae aspernatur quo suscipit voluptatem',
                'user_id' => 1,
            ),
            array(
                'name' => 'Extensão',
                'sigla' => 'Exte',
                'introd' => 'Consequuntur inventore voluptates consequatur aut vel et. Eos doloribus expedita. Sapiente atque consequatur minima nihil quae aspernatur quo suscipit voluptatem',
                'user_id' => 1,
            ),
            array(
                'name' => 'Pesquisa e Inovação',
                'sigla' => 'Pesq',
                'introd' => 'Consequuntur inventore voluptates consequatur aut vel et. Eos doloribus expedita. Sapiente atque consequatur minima nihil quae aspernatur quo suscipit voluptatem',
                'user_id' => 1,
            ),
            array(
                'name' => 'Internacionalização',
                'sigla' => 'Inter',
                'introd' => 'Consequuntur inventore voluptates consequatur aut vel et. Eos doloribus expedita. Sapiente atque consequatur minima nihil quae aspernatur quo suscipit voluptatem',
                'user_id' => 1,
            ),
            array(
                'name' => 'Gestão e Organização',
                'sigla' => 'Gestão',
                'introd' => 'Consequuntur inventore voluptates consequatur aut vel et. Eos doloribus expedita. Sapiente atque consequatur minima nihil quae aspernatur quo suscipit voluptatem',
                'user_id' => 1,
            ),
            array(
                'name' => 'Gestão de Pessoas',
                'sigla' => 'RecHum',
                'introd' => 'Consequuntur inventore voluptates consequatur aut vel et. Eos doloribus expedita. Sapiente atque consequatur minima nihil quae aspernatur quo suscipit voluptatem',
                'user_id' => 1,
            ),
            array(
                'name' => 'Infraestrutura',
                'sigla' => 'Infra',
                'introd' => 'Consequuntur inventore voluptates consequatur aut vel et. Eos doloribus expedita. Sapiente atque consequatur minima nihil quae aspernatur quo suscipit voluptatem',
                'user_id' => 1,
            ),
            array(
                'name' => 'Planejamento e Avaliação Institucional',
                'sigla' => 'Aval',
                'introd' => 'Consequuntur inventore voluptates consequatur aut vel et. Eos doloribus expedita. Sapiente atque consequatur minima nihil quae aspernatur quo suscipit voluptatem',
                'user_id' => 1,
            ),
            array(
                'name' => 'Assistência Estudantil',
                'sigla' => 'AssitEstud',
                'introd' => 'Consequuntur inventore voluptates consequatur aut vel et. Eos doloribus expedita. Sapiente atque consequatur minima nihil quae aspernatur quo suscipit voluptatem',
                'user_id' => 1,
            ),
            array(
                'name' => 'Responsabilidade Social e Ações Afirmativas',
                'sigla' => 'AcAfirm',
                'introd' => 'Consequuntur inventore voluptates consequatur aut vel et. Eos doloribus expedita. Sapiente atque consequatur minima nihil quae aspernatur quo suscipit voluptatem',
                'user_id' => 1,
            ),
            array(
                'name' => 'Comunicação e Cultura',
                'sigla' => 'Comunic',
                'introd' => 'Consequuntur inventore voluptates consequatur aut vel et. Eos doloribus expedita. Sapiente atque consequatur minima nihil quae aspernatur quo suscipit voluptatem',
                'user_id' => 1,
            ),
            array(
                'name' => 'Tecnologia e Conectividade',
                'sigla' => 'TecCon',
                'introd' => 'Consequuntur inventore voluptates consequatur aut vel et. Eos doloribus expedita. Sapiente atque consequatur minima nihil quae aspernatur quo suscipit voluptatem',
                'user_id' => 1,
            ),
        );

        foreach ($dimensions as $dimension) {
            DB::table('dimensions')->insert($dimension);
        }

        $eixos[] = array(
            array(
                'name' => '1 - Formação cidadã e profissional',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 1,
                'user_id' => 1
            ),
            array(
                'name' => '2 - Produção e difusão do conhecimento ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 1,
                'user_id' => 1
            ),
            array(
                'name' => '3 - Acesso e permanência com qualidade ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 1,
                'user_id' => 1
            ),
            array(
                'name' => '4 - Articulação universidade e sociedade',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 1,
                'user_id' => 1
            ),
            array(
                'name' => '5 - Democratização, descentralização e transparência',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 1,
                'user_id' => 1
            ),
            array(
                'name' => '1 - Formação cidadã e profissional',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 2,
                'user_id' => 1
            ),
            array(
                'name' => '2 - Produção e difusão do conhecimento ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 2,
                'user_id' => 1
            ),
            array(
                'name' => '3 - Acesso e permanência com qualidade ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 2,
                'user_id' => 1
            ),
            array(
                'name' => '4 - Articulação universidade e sociedade',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 2,
                'user_id' => 1
            ),
            array(
                'name' => '5 - Democratização, descentralização e transparência',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 2,
                'user_id' => 1
            ),
            array(
                'name' => '1 - Formação cidadã e profissional',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 3,
                'user_id' => 1
            ),
            array(
                'name' => '2 - Produção e difusão do conhecimento ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 3,
                'user_id' => 1
            ),
            array(
                'name' => '3 - Acesso e permanência com qualidade ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 3,
                'user_id' => 1
            ),
            array(
                'name' => '4 - Articulação universidade e sociedade',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 3,
                'user_id' => 1
            ),
            array(
                'name' => '5 - Democratização, descentralização e transparência',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 3,
                'user_id' => 1
            ),
            array(
                'name' => '1 - Formação cidadã e profissional',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 4,
                'user_id' => 1
            ),
            array(
                'name' => '2 - Produção e difusão do conhecimento ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 4,
                'user_id' => 1
            ),
            array(
                'name' => '3 - Acesso e permanência com qualidade ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 4,
                'user_id' => 1
            ),
            array(
                'name' => '4 - Articulação universidade e sociedade',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 4,
                'user_id' => 1
            ),
            array(
                'name' => '5 - Democratização, descentralização e transparência',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 4,
                'user_id' => 1
            ),
            array(
                'name' => '1 - Formação cidadã e profissional',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 5,
                'user_id' => 1
            ),
            array(
                'name' => '2 - Produção e difusão do conhecimento ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 5,
                'user_id' => 1
            ),
            array(
                'name' => '3 - Acesso e permanência com qualidade ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 5,
                'user_id' => 1
            ),
            array(
                'name' => '4 - Articulação universidade e sociedade',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 5,
                'user_id' => 1
            ),
            array(
                'name' => '5 - Democratização, descentralização e transparência',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 5,
                'user_id' => 1
            ),
            array(
                'name' => '1 - Formação cidadã e profissional',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 6,
                'user_id' => 1
            ),
            array(
                'name' => '2 - Produção e difusão do conhecimento ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 6,
                'user_id' => 1
            ),
            array(
                'name' => '3 - Acesso e permanência com qualidade ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 6,
                'user_id' => 1
            ),
            array(
                'name' => '4 - Articulação universidade e sociedade',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 6,
                'user_id' => 1
            ),
            array(
                'name' => '5 - Democratização, descentralização e transparência',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 6,
                'user_id' => 1
            ),
            array(
                'name' => '1 - Formação cidadã e profissional',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 7,
                'user_id' => 1
            ),
            array(
                'name' => '2 - Produção e difusão do conhecimento ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 7,
                'user_id' => 1
            ),
            array(
                'name' => '3 - Acesso e permanência com qualidade ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 7,
                'user_id' => 1
            ),
            array(
                'name' => '4 - Articulação universidade e sociedade',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 7,
                'user_id' => 1
            ),
            array(
                'name' => '5 - Democratização, descentralização e transparência',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 7,
                'user_id' => 1
            ),
            array(
                'name' => '1 - Formação cidadã e profissional',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 8,
                'user_id' => 1
            ),
            array(
                'name' => '2 - Produção e difusão do conhecimento ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 8,
                'user_id' => 1
            ),
            array(
                'name' => '3 - Acesso e permanência com qualidade ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 8,
                'user_id' => 1
            ),
            array(
                'name' => '4 - Articulação universidade e sociedade',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 8,
                'user_id' => 1
            ),
            array(
                'name' => '5 - Democratização, descentralização e transparência',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 8,
                'user_id' => 1
            ),
            array(
                'name' => '1 - Formação cidadã e profissional',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 9,
                'user_id' => 1
            ),
            array(
                'name' => '2 - Produção e difusão do conhecimento ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 9,
                'user_id' => 1
            ),
            array(
                'name' => '3 - Acesso e permanência com qualidade ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 9,
                'user_id' => 1
            ),
            array(
                'name' => '4 - Articulação universidade e sociedade',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 9,
                'user_id' => 1
            ),
            array(
                'name' => '5 - Democratização, descentralização e transparência',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 9,
                'user_id' => 1
            ),
            array(
                'name' => '1 - Formação cidadã e profissional',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'Pouca utilização de registros e dados pelos gestores acadêmicos#Pouca utilização de registros e dados  pela gestão superior',
                'oport' => 'Consolidação do Portal da Avaliação Institucional',
                'ameac' => 'Baixo desempenho de alguns cursos (com nota 1 ou 2 no ENADE e CPC)',
                'publica' => 's',
                'dimension_id' => 10,
                'user_id' => 1
            ),
            array(
                'name' => '2 - Produção e difusão do conhecimento ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 10,
                'user_id' => 1
            ),
            array(
                'name' => '3 - Acesso e permanência com qualidade ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 10,
                'user_id' => 1
            ),
            array(
                'name' => '4 - Articulação universidade e sociedade',
                'descr' => 'null',
                'forca' => 'Disponibilização de dados acadêmicos consolidados através do Anuário UNEB em Dados#Consolidação de dados institucionais em plataformas oficiais (e-MEC)',
                'fraqu' => 'null',
                'oport' => 'Atualização do Plano de Desenvolvimento Institucional#Reconstituição da CPA e revisão conceitual de sua atuação#Manutenção da nota IGC que qualifica a Universidade',
                'ameac' => 'Pouca participação da Universidade nos Programas do Plano Plurianual (PPA)',
                'publica' => 's',
                'dimension_id' => 10,
                'user_id' => 1
            ),
            array(
                'name' => '5 - Democratização, descentralização e transparência',
                'descr' => 'null',
                'forca' => 'Desenvolvimento de indicadores de acompanhamento de curso junto a Departamentos/colegiados de curso#Implementação de novo sistema de emissão de diplomas (SRDC)#Mobilização da comunidade acadêmica para participação no ENADE#Implantação de aplicativo para dispositivos móveis (caderneta mobile)#Consolidação de registros e dados acadêmicos a partir da SEAVI/SGC/UDO/SERDIC#Sistematização de metodologia para prestação de informação ao INEP (Censo da educação superior)#Alinhamento de procedimentos entre SEAVI, SGC e Departamentos para registros acadêmicos#Melhoria do atendimento às políticas nacionais de avaliação (MEC e INEP)#Implantação do Sistema Informatizado de Planejamento e Gestão Universitária (SPGU)#Articulação entre os processos de planejamento e avaliação institucional#Regulamentação para implementação do orçamento participativo',
                'fraqu' => 'Composição funcional da SEAVI#Dificuldades de articulação entre setores da administração superior para desenvolvimento de processos avaliativos#Dificudade para composição do quadro  da CPA#Dificuldade de atuação da CPA#Atendimento de demandas por informações em caráter de urgência#Desatualização do Sistema Informatizado de Planejamento (SIP)#Cultura de planejamento institucional incipiente#Dificuldade na obtenção de informações sobre as atividades desenvolvidas no âmbito da Universidade#Pouca participação da comunidade universitária na elaboração da proposta orçamentária',
                'oport' => 'Articulação com as Secretarias de Planejamento e Fazenda (Seplan e Sefaz)',
                'ameac' => 'Contigenciamento dos recursos financeiros em relação ao orçamento aprovado',
                'publica' => 's',
                'dimension_id' => 10,
                'user_id' => 1
            ),
            array(
                'name' => '1 - Formação cidadã e profissional',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 11,
                'user_id' => 1
            ),
            array(
                'name' => '2 - Produção e difusão do conhecimento ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 11,
                'user_id' => 1
            ),
            array(
                'name' => '3 - Acesso e permanência com qualidade ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 11,
                'user_id' => 1
            ),
            array(
                'name' => '4 - Articulação universidade e sociedade',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 11,
                'user_id' => 1
            ),
            array(
                'name' => '5 - Democratização, descentralização e transparência',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 11,
                'user_id' => 1
            ),
            array(
                'name' => '1 - Formação cidadã e profissional',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 12,
                'user_id' => 1
            ),
            array(
                'name' => '2 - Produção e difusão do conhecimento ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 12,
                'user_id' => 1
            ),
            array(
                'name' => '3 - Acesso e permanência com qualidade ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 12,
                'user_id' => 1
            ),
            array(
                'name' => '4 - Articulação universidade e sociedade',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 12,
                'user_id' => 1
            ),
            array(
                'name' => '5 - Democratização, descentralização e transparência',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 12,
                'user_id' => 1
            ),
            array(
                'name' => '1 - Formação cidadã e profissional',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 13,
                'user_id' => 1
            ),
            array(
                'name' => '2 - Produção e difusão do conhecimento ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 13,
                'user_id' => 1
            ),
            array(
                'name' => '3 - Acesso e permanência com qualidade ',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 13,
                'user_id' => 1
            ),
            array(
                'name' => '4 - Articulação universidade e sociedade',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 13,
                'user_id' => 1
            ),
            array(
                'name' => '5 - Democratização, descentralização e transparência',
                'descr' => 'null',
                'forca' => 'null',
                'fraqu' => 'null',
                'oport' => 'null',
                'ameac' => 'null',
                'publica' => 's',
                'dimension_id' => 13,
                'user_id' => 1
            ),
        );

        foreach ($eixos as $eixo){
            DB::table('eixos')->insert($eixo);
        }
    }
}
